### ISSUE TITLE
AMA (Ask Me Anything)

### ISSUE THREAD

**Issue by yakushou730** [yakushou730/profiles#1]
```
{
  "username": "yakushou730",
  "name": "Shou Tseng",
  "projects": [
    "not decided yet"
  ],
  "background":[
    "Back-end Developer",
    "Ruby on Rails 2 years",
    "Know basic HTML, CSS, Javascript for front-end"
  ],
  "interests":[
    "Learning new programming skills"
  ],
  "twitter": "",
  "github": "https://github.com/YaoShangTseng"
}
```

**Comment by serapath** [comment]
I saw you did not list any `"projects"` :-)

Just wanted to say a little sorry for not making clear what was meant by that.
A project was meant as being something open source (learning or working on something) during the codecamp for you to do.

It is good enough to be just a fuzzy idea in the beginning. You would make an empty github repository and include a little description what topics it is supposed to be about.

Then you would present it in your `AMA` and also go around to other people on the codecamp to see what they are planning to work on or learn during the codecamp.

If you find beginners, maybe you can offer some mentoring and they would practice to do some little tasks for your projects.
If you find other people with more experience, maybe you can adapt your project to either learn together with them - everyone figures out something and you present to each other - or to work together with, so then what you with others build would be:
* a module that others can `require` or `import`
* a tool or app that others can include in their app as an embedded iframe
* if its backend or a blockchain smart contract - then they can interact via API

**Comment by serapath** [comment]
did you already make a github repository for your project idea and have a link?

**Comment by serapath** [comment]
hey hey, how is it going? :-)

**Comment by yakushou730** [comment]
uh... I'm sorry for this. But my workload is heavy at office currently.
I think it's quite hard to programming a project. : (
But at least I hope I can try solidity & web3.js with the learning resources.

**Comment by serapath** [comment]
no problem. Would be sweet if you try.
There are quite a few others who also learn.
If you publish you learning progress on github and share the link, that would be sweet.
https://github.com/wizardamigos/skilltree#smart-contracts-ethereum-based
